<?xml version="1.0" encoding="UTF-8"?>

<!-- Internal DTD declaration-->

<!DOCTYPE patientsList [  
  <!ELEMENT patient (Patient_ID, Age, Gender, Protein1, Protein2, Protein3, Protein4, Tumour_Stage, Histology, ER_status, PR_status, HER2_status, Surgery_type, Date_of_Surgery, Date_of_Last_Visit, Patient_Status)>
  
  <!ELEMENT Patient_ID (#PCDATA)>
  <!ELEMENT Age (#PCDATA)>
  <!ELEMENT Gender (#PCDATA)>
  <!ELEMENT Protein1 (#PCDATA)>
  <!ELEMENT Protein2 (#PCDATA)>
  <!ELEMENT Protein3 (#PCDATA)>
  <!ELEMENT Protein4 (#PCDATA)>
  <!ELEMENT Tumour_Stage (#PCDATA)>
  <!ELEMENT Histology (#PCDATA)>
  <!ELEMENT ER_status (#PCDATA)>
  <!ELEMENT PR_status (#PCDATA)>
  <!ELEMENT HER2_status (#PCDATA)>
  <!ELEMENT Surgery_type (#PCDATA)>
  <!ELEMENT Date_of_Surgery (#PCDATA)>
  <!ELEMENT Date_of_Last_Visit (#PCDATA)>
  <!ELEMENT Patient_Status (#PCDATA)>
]>

<!-- XML -->
<!-- Patients information -->
<patientsList> <!-- root node -->
  <patient>
    <Patient_ID>TCGA-D8-A1XD</Patient_ID>
    <Age>36</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.080353</Protein1>
    <Protein2>0.42638</Protein2>
    <Protein3>0.54715</Protein3>
    <Protein4>0.27368</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>15-Jan-17</Date_of_Surgery>
    <Date_of_Last_Visit>19-Jun-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-EW-A1OX</Patient_ID>
    <Age>43</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.42032</Protein1>
    <Protein2>0.57807</Protein2>
    <Protein3>0.61447</Protein3>
    <Protein4>-0.031505</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Mucinous Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>26-Apr-17</Date_of_Surgery>
    <Date_of_Last_Visit>09-Nov-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A8-A079</Patient_ID>
    <Age>69</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.21398</Protein1>
    <Protein2>1.3114</Protein2>
    <Protein3>-0.32747</Protein3>
    <Protein4>-0.23426</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>08-Sep-17</Date_of_Surgery>
    <Date_of_Last_Visit>09-Jun-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-D8-A1XR</Patient_ID>
    <Age>56</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.34509</Protein1>
    <Protein2>-0.21147</Protein2>
    <Protein3>-0.19304</Protein3>
    <Protein4>0.12427</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>25-Jan-17</Date_of_Surgery>
    <Date_of_Last_Visit>12-Jul-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A0BF</Patient_ID>
    <Age>56</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.22155</Protein1>
    <Protein2>1.9068</Protein2>
    <Protein3>0.52045</Protein3>
    <Protein4>-0.31199</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>06-May-17</Date_of_Surgery>
    <Date_of_Last_Visit>27-Jun-19</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AO-A1KQ</Patient_ID>
    <Age>84</Age>
    <Gender>MALE</Gender>
    <Protein1>-0.081872</Protein1>
    <Protein2>1.7241</Protein2>
    <Protein3>-0.057335</Protein3>
    <Protein4>0.043025</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>18-Sep-17</Date_of_Surgery>
    <Date_of_Last_Visit>15-Nov-21</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-D8-A73X</Patient_ID>
    <Age>53</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.069535</Protein1>
    <Protein2>1.4183</Protein2>
    <Protein3>-0.36105</Protein3>
    <Protein4>0.39158</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>04-Feb-17</Date_of_Surgery>
    <Date_of_Last_Visit>07-Feb-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A7-A426</Patient_ID>
    <Age>50</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.67249</Protein1>
    <Protein2>1.279</Protein2>
    <Protein3>-0.32107</Protein3>
    <Protein4>-0.11239</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>16-May-17</Date_of_Surgery>
    <Date_of_Last_Visit></Date_of_Last_Visit>
    <Patient_Status></Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-EW-A1P5</Patient_ID>
    <Age>77</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.15175</Protein1>
    <Protein2>-0.66332</Protein2>
    <Protein3>1.1894</Protein3>
    <Protein4>0.21718</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>28-Sep-17</Date_of_Surgery>
    <Date_of_Last_Visit>28-Sep-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A8-A09A</Patient_ID>
    <Age>40</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.5657</Protein1>
    <Protein2>1.2668</Protein2>
    <Protein3>-0.29346</Protein3>
    <Protein4>0.19395</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Positive</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>14-Feb-17</Date_of_Surgery>
    <Date_of_Last_Visit>15-Dec-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-S3-A6ZG</Patient_ID>
    <Age>71</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.22305</Protein1>
    <Protein2>0.50594</Protein2>
    <Protein3>-0.34943</Protein3>
    <Protein4>-0.8353</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>26-May-17</Date_of_Surgery>
    <Date_of_Last_Visit>19-Dec-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A0EA</Patient_ID>
    <Age>72</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.3727</Protein1>
    <Protein2>0.55549</Protein2>
    <Protein3>-0.6679</Protein3>
    <Protein4>-0.3507</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>08-Oct-17</Date_of_Surgery>
    <Date_of_Last_Visit>13-Sep-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AC-A8OR</Patient_ID>
    <Age>75</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.17164</Protein1>
    <Protein2>0.029656</Protein2>
    <Protein3>-0.1589</Protein3>
    <Protein4>0.67471</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>24-Feb-17</Date_of_Surgery>
    <Date_of_Last_Visit>05-Apr-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A2-A0ES</Patient_ID>
    <Age>52</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-1.6828</Protein1>
    <Protein2>0.72722</Protein2>
    <Protein3>0.056773</Protein3>
    <Protein4>-1.2441</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>05-Jun-17</Date_of_Surgery>
    <Date_of_Last_Visit>02-Mar-20</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-C8-A8HQ</Patient_ID>
    <Age>53</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.56042</Protein1>
    <Protein2>0.82251</Protein2>
    <Protein3>-0.53476</Protein3>
    <Protein4>0.26527</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Mucinous Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>18-Oct-17</Date_of_Surgery>
    <Date_of_Last_Visit>28-Apr-20</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AO-A03V</Patient_ID>
    <Age>41</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.14252</Protein1>
    <Protein2>1.0827</Protein2>
    <Protein3>0.21092</Protein3>
    <Protein4>0.97428</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>06-Mar-17</Date_of_Surgery>
    <Date_of_Last_Visit>09-Aug-19</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A2-A0D4</Patient_ID>
    <Age>37</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.2949</Protein1>
    <Protein2>1.3625</Protein2>
    <Protein3>0.69238</Protein3>
    <Protein4>0.41002</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Mucinous Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>15-Jun-17</Date_of_Surgery>
    <Date_of_Last_Visit>24-Oct-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-EW-A1PA</Patient_ID>
    <Age>59</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.19762</Protein1>
    <Protein2>1.0719</Protein2>
    <Protein3>-0.2051</Protein3>
    <Protein4>0.63315</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>28-Oct-17</Date_of_Surgery>
    <Date_of_Last_Visit>22-Jul-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A0DE</Patient_ID>
    <Age>62</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.10464</Protein1>
    <Protein2>0.7028</Protein2>
    <Protein3>-0.29898</Protein3>
    <Protein4>0.60103</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>16-Mar-17</Date_of_Surgery>
    <Date_of_Last_Visit>20-Oct-19</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-E2-A1B4</Patient_ID>
    <Age>74</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.24613</Protein1>
    <Protein2>1.4953</Protein2>
    <Protein3>-0.29854</Protein3>
    <Protein4>0.65925</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>25-Jun-17</Date_of_Surgery>
    <Date_of_Last_Visit>23-Dec-19</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AC-A3HN</Patient_ID>
    <Age>87</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.087485</Protein1>
    <Protein2>1.1111</Protein2>
    <Protein3>-0.56692</Protein3>
    <Protein4>1.2237</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>07-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit>28-Nov-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A8-A095</Patient_ID>
    <Age>45</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.59518</Protein1>
    <Protein2>-0.34054</Protein2>
    <Protein3>0.44454</Protein3>
    <Protein4>0.75328</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>26-Mar-17</Date_of_Surgery>
    <Date_of_Last_Visit>23-Sep-20</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AN-A0FY</Patient_ID>
    <Age>55</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.33064</Protein1>
    <Protein2>0.84757</Protein2>
    <Protein3>-0.49466</Protein3>
    <Protein4>0.11656</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>07-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit></Date_of_Last_Visit>
    <Patient_Status></Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A2-A4S0</Patient_ID>
    <Age>77</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.2987</Protein1>
    <Protein2>-0.16129</Protein2>
    <Protein3>0.46072</Protein3>
    <Protein4>-0.39666</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>17-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit>15-Aug-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A7-A3J0</Patient_ID>
    <Age>62</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.5424</Protein1>
    <Protein2>1.7926</Protein2>
    <Protein3>-0.56599</Protein3>
    <Protein4>-0.017206</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>05-Apr-17</Date_of_Surgery>
    <Date_of_Last_Visit>20-Jun-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AC-A62Y</Patient_ID>
    <Age>79</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.036229</Protein1>
    <Protein2>0.79551</Protein2>
    <Protein3>-0.013525</Protein3>
    <Protein4>1.6299</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Mucinous Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Positive</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>17-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit>11-Jan-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A7-A5ZW</Patient_ID>
    <Age>47</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.33186</Protein1>
    <Protein2>-0.32765</Protein2>
    <Protein3>0.0033786</Protein3>
    <Protein4>1.1658</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Mucinous Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>27-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit>10-Apr-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A2-A25C</Patient_ID>
    <Age>50</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.062153</Protein1>
    <Protein2>1.612</Protein2>
    <Protein3>-0.47404</Protein3>
    <Protein4>-0.044448</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>15-Apr-17</Date_of_Surgery>
    <Date_of_Last_Visit>25-Jan-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-D8-A1JC</Patient_ID>
    <Age>59</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.33045</Protein1>
    <Protein2>1.4353</Protein2>
    <Protein3>-0.608</Protein3>
    <Protein4>-0.3507</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>27-Nov-17</Date_of_Surgery>
    <Date_of_Last_Visit>24-May-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A7-A4SB</Patient_ID>
    <Age>56</Age>
    <Gender>FEMALE</Gender>
    <Protein1>1.0352</Protein1>
    <Protein2>1.7646</Protein2>
    <Protein3>-0.75921</Protein3>
    <Protein4>0.97527</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Positive</HER2 status>
    <Surgery_type>Lumpectomy</Surgery_type>
    <Date_of_Surgery>07-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>25-Jun-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AR-A24S</Patient_ID>
    <Age>61</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.22788</Protein1>
    <Protein2>1.7908</Protein2>
    <Protein3>-0.75621</Protein3>
    <Protein4>0.73977</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>25-Apr-17</Date_of_Surgery>
    <Date_of_Last_Visit>26-Jun-22</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-D8-A4Z1</Patient_ID>
    <Age>68</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.64903</Protein1>
    <Protein2>1.424</Protein2>
    <Protein3>-0.39536</Protein3>
    <Protein4>1.1848</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>07-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>18-Jul-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A7-A26J</Patient_ID>
    <Age>49</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.28082</Protein1>
    <Protein2>0.71925</Protein2>
    <Protein3>-0.171</Protein3>
    <Protein4>0.54672</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>17-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>23-Feb-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AC-A5XS</Patient_ID>
    <Age>74</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.59453</Protein1>
    <Protein2>0.94863</Protein2>
    <Protein3>-0.49834</Protein3>
    <Protein4>0.97173</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>05-May-17</Date_of_Surgery>
    <Date_of_Last_Visit>21-Jun-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-OL-A6VR</Patient_ID>
    <Age>48</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.23235</Protein1>
    <Protein2>1.2129</Protein2>
    <Protein3>0.052518</Protein3>
    <Protein4>-0.024126</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>17-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>13-Apr-20</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-EW-A1PF</Patient_ID>
    <Age>50</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.079765</Protein1>
    <Protein2>2.6229</Protein2>
    <Protein3>0.049687</Protein3>
    <Protein4>-0.039369</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>27-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>16-May-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-LL-A7SZ</Patient_ID>
    <Age>49</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.061643</Protein1>
    <Protein2>1.3149</Protein2>
    <Protein3>-0.099357</Protein3>
    <Protein4>0.75441</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>15-May-17</Date_of_Surgery>
    <Date_of_Last_Visit>01-Nov-17</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A18K</Patient_ID>
    <Age>46</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.55214</Protein1>
    <Protein2>2.0836</Protein2>
    <Protein3>0.41605</Protein3>
    <Protein4>-0.80791</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>27-Dec-17</Date_of_Surgery>
    <Date_of_Last_Visit>02-Dec-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-AC-A3OD</Patient_ID>
    <Age>68</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.34962</Protein1>
    <Protein2>1.3735</Protein2>
    <Protein3>-0.24356</Protein3>
    <Protein4>0.18804</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>06-Jan-18</Date_of_Surgery>
    <Date_of_Last_Visit>10-Feb-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A8FY</Patient_ID>
    <Age>87</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.70876</Protein1>
    <Protein2>2.1731</Protein2>
    <Protein3>-0.43967</Protein3>
    <Protein4>-0.39255</Protein4>
    <Tumour_Stage>I</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>
    <Date_of_Surgery>25-May-17</Date_of_Surgery>
    <Date_of_Last_Visit>15-Jan-18</Date_of_Last_Visit>
    <Patient_Status>Dead</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-C8-A26Z</Patient_ID>
    <Age>59</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.28025</Protein1>
    <Protein2>0.89896</Protein2>
    <Protein3>-0.61003</Protein3>
    <Protein4>0.53418</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>06-Jan-18</Date_of_Surgery>
    <Date_of_Last_Visit>10-Jan-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-A2-A1G4</Patient_ID>
    <Age>71</Age>
    <Gender>FEMALE</Gender>
    <Protein1>-0.9484</Protein1>
    <Protein2>0.74051</Protein2>
    <Protein3>-0.25829</Protein3>
    <Protein4>-0.21336</Protein4>
    <Tumour_Stage>III</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Modified Radical Mastectomy</Surgery_type>
    <Date_of_Surgery>16-Jan-18</Date_of_Surgery>
    <Date_of_Last_Visit>23-Jan-19</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-BH-A18F</Patient_ID>
    <Age>50</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.21728</Protein1>
    <Protein2>-0.21628</Protein2>
    <Protein3>1.0881</Protein3>
    <Protein4>0.15429</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Lobular Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Other</Surgery_type>
    <Date_of_Surgery>04-Jun-17</Date_of_Surgery>
    <Date_of_Last_Visit>27-Feb-18</Date_of_Last_Visit>
    <Patient_Status>Alive</Patient_Status>
  </patient>
  <patient>
    <Patient_ID>TCGA-E2-A1IG</Patient_ID>
    <Age>45</Age>
    <Gender>FEMALE</Gender>
    <Protein1>0.42538</Protein1>
    <Protein2>1.2628</Protein2>
    <Protein3>-0.71996</Protein3>
    <Protein4>-1.1641</Protein4>
    <Tumour_Stage>II</Tumour_Stage>
    <Histology>Infiltrating Ductal Carcinoma</Histology>
    <ER status>Positive</ER status>
    <PR status>Positive</PR status>
    <HER2 status>Negative</HER2 status>
    <Surgery_type>Simple Mastectomy</Surgery_type>